### ISSUE TITLE
[Question] Future plans for compatibility with Bedspreads?

### ISSUE THREAD

**Issue by chimericdream** [EliteAsian123/BannerAdditions#8]
I came across this mod while browsing through CurseForge, and I think it looks cool. However, I saw on the mod page that it isn't compatible with Bedspreads, which is something we already have in our modpack. Is that due to some conflict between the two mods in how they modify banner functionality, or is it simply something you noticed and have on a "do something about this in the future maybe" list? I'd love to use both mods, but understand if there's a technical reason why they cannot be made to work together.

**Comment by EliteAsian123** [comment]
Hello, thanks for the issue report! Because of how BannerAdditions changes banners, a full rewrite of Bedspreads would be necessary in order for it to work with BannerAdditions. So unfortunately, Bedspreads will probably never work with BannerAdditions and I have no plans on making it work. Sorry for the inconvenience and I wish you luck on your modpack.

**Comment by chimericdream** [comment]
I understand. Thanks for the response!
